import { News } from "../../types/news";

export const newsData: News[] = [
  {
    id: "1",
    title: "iOS 16.4 Second Test Hints Superb New iPhone Feature Is Near",
    content:
      "Apple has just issued a second test of its superb new security feature, Rapid Security Response, in the iOS 16.4 Beta version. The latest test of the feature was released",
    category: "Technology",
    readTime: 4,
    upvotes: 15,
    isVerified: true,
    date: "Less than 1hr ago",
  },
  {
    id: "2",
    title: "WhatsApp Will Soon Let Users Choose when Group Chats Will Expire",
    content:
      "If you've ever created or joined a WhatsApp group chat for a single event, then kept forgetting to delete it for years afterwards, there's an upcoming feature you may appreciate",
    category: "Technology",
    readTime: 2,
    upvotes: 10,
    isVerified: false,
    date: "1hr ago",
  },
  {
    id: "3",
    title: "Microsoft Debuts a New 'Velocity Green' Xbox Controller",
    content:
      " There are certain colors you see and have an immediate association. For gamers, one of the most iconic might be that warm medium green seen on Yoshi and, most",
    category: "Technology",
    readTime: 4,
    upvotes: 30,
    isVerified: true,
    date: "2hrs ago",
  },
  //   {
  //     id: "1",
  //     title: "",
  //     content: "",
  //     category: "",
  //     readTime: "",
  //     upvotes: "",
  //     isVerified: "",
  //     date: "",
  //   },
  //   {
  //     id: "1",
  //     title: "",
  //     content: "",
  //     category: "",
  //     readTime: "",
  //     upvotes: "",
  //     isVerified: "",
  //     date: "",
  //   },
  //   {
  //     id: "1",
  //     title: "",
  //     content: "",
  //     category: "",
  //     readTime: "",
  //     upvotes: "",
  //     isVerified: "",
  //     date: "",
  //   },
  //   {
  //     id: "1",
  //     title: "",
  //     content: "",
  //     category: "",
  //     readTime: "",
  //     upvotes: "",
  //     isVerified: "",
  //     date: "",
  //   },
  //   {
  //     id: "1",
  //     title: "",
  //     content: "",
  //     category: "",
  //     readTime: "",
  //     upvotes: "",
  //     isVerified: "",
  //     date: "",
  //   },
];
